### ISSUE TITLE
Does it need to say "for the purposes of this PP"

### ISSUE THREAD

**Issue by woodbe** [commoncriteria/mobile-device#11]
It isn't clear that it is necessary to say "for the purposes of this PP" in 
https://github.com/commoncriteria/mobile-device/blob/4de420d946cd352646d3a73ed2a9f296db02ffeb/input/mobile-device.xml#L219-L220

I think it would be better to either state in the initial description of the system that all components, including data storage, are container within the TOE, or to add such a statement to the Biometric Data description, pointing out that all biometric data must be stored locally. 

Either way, the statement about it being for this PP seems unneeded.

**Comment by zsmi** [comment]
Closed with commit b04c2a5bb01175172cef246d2895bd19a0b918d5
