### ISSUE TITLE
Operating System definition incomplete

### ISSUE THREAD

**Issue by woodbe** [commoncriteria/mobile-device#14]
The OS definition describes 2 operating systems, one for the AP and one for the BP. Then, when you get to the Rich OS definition, there is another operating system for the isolated execution environment. 

While I don't necessarily dispute that there is some sort of OS on the BP, there are no requirements on that OS, only about interactions between the AP and the BP, while there are more specific requirements about the isolated execution environment (even if there aren't specific demands of it directly).

The OS definition should include the restricted OS at a minimum. I would also probably remove the BP OS from the definition, though as long as the restricted OS is added, I think it is sufficient.

**Comment by woodbe** [comment]
There is a general question here though about why it is necessary to actually define the "Rich OS" since the Rich OS is the only OS with any requirements directly laid on it in the PP.

Should there be a separate definition of a "Trusted" OS (or the Secure Execution Environment definition used in the Biometrics PP-Module for this specific purpose)?

**Comment by lewyble** [comment]
All references to "Rich OS" have been changed to simply "OS" which per the definition of Operating System is equivalent to the OS running on the Application Processor.
