### ISSUE TITLE
WLAN Client EP conformance

### ISSUE THREAD

**Issue by woodbe** [commoncriteria/mobile-device#17]
I get that the WLAN Client EP is not currently structured as a PP-Module, but it seems strange to not see it included as part of the conformance claims.
https://github.com/commoncriteria/mobile-device/blob/4de420d946cd352646d3a73ed2a9f296db02ffeb/input/mobile-device.xml#L569-L578

Maybe it should be listed as part of the Package Claims at this point?

If it isn't listed here, exactly how should it be listed in a ST, especially with Exact Conformance. The WLAN Client EP is referenced in several places in the document, but how can it be claimed if there is not conformance to it anywhere?

**Comment by lewyble** [comment]
@dmhale1 -- Thoughts?

**Comment by dmhale1** [comment]
So this section doesn't mean that the MDF claims conformance to the PP-Modules. It just says they can be used together. But CC doesn't have rules for EPs as they aren't really a thing. So, we don't put them in the PPs. So for an ST, you would claim compliance to  a PP-Configuration that includes MDF w/BT and/or VPN Client. And, a separate claim to the WLAN EP.

**Comment by lewyble** [comment]
No changes were made to the PP. However, when WLAN Client EP is updated to a PP-Module, it will be added to this section.
