### ISSUE TITLE
Draft Candidate V3.2

### ISSUE THREAD

**Issue by The-Fiona** [commoncriteria/mobile-device#2]
In section 2. Conformance Claim, the following text appears.
"An ST must claim exact conformance to this PP, as defined in the CC and CEM addenda for Exact Conformance"

The term "Exact Conformance" does not appear in CC 3.1R5 or the associated addenda. So this statement is (currently) incorrect. Hint: Some apps define the term within the body of the cPP as a way of navigating this issue.

**Comment by dmhale1** [comment]
Exact conformance is defined on page 6 of the addenda.

**Comment by lewyble** [comment]
@dmhale1 - I know we talked about this a while ago, but I can't remember. Do I need to make any changes to the PP to address this issue? If no changes are needed please close out the comment. Thanks!

**Comment by dmhale1** [comment]
No change neede.
