### ISSUE TITLE
Remove WPA2 here?

### ISSUE THREAD

**Issue by woodbe** [commoncriteria/mobile-device#27]
I'm wondering if WPA2 should be removed here and instead just say Wi-Fi PSKs

https://github.com/commoncriteria/mobile-device/blob/954ded4330200e30c1e4b35b7b7398b6d6a3598c/input/mobile-device.xml#L3577-L3582

My thinking is that when WPA3 becomes accepted that having this just be Wi-Fi PSKs would mean it doesn't still need to be adjusted. I do get that this is likely to come with something like an updated Wi-Fi PP-Module which will mean edits here anyway, but it seems like the type of thing that would just be simple to edit here and leave alone in the future.

**Comment by lewyble** [comment]
Fixed.
