### ISSUE TITLE
FCS_STG_EXT.2 Sensitive Data & Glossary

### ISSUE THREAD

**Issue by woodbe** [commoncriteria/mobile-device#29]
This has come up in the past, but the term Sensitive Data is defined in the glossary to be application data as well as some key data. How exactly can key data be considered the same as the application data that is protected by the keys?

I think the key data should be called something else (Sensitive Keys?), because how keys are stored and protected is necessarily different than how data marked as Sensitive will be protected. 

I get that the point is that keys need to be protected by multiple keys, but keys and data should be separate each other and not use the same terms and even be emphasized that they are the same.
https://github.com/commoncriteria/mobile-device/blob/954ded4330200e30c1e4b35b7b7398b6d6a3598c/input/mobile-device.xml#L3570-L3572

**Comment by lewyble** [comment]
Removed any reference to keys from protected or sensitive data. Did not add a new term (i.e., sensitive keys). The protection requirements for REK, DEK, and KEK are already defined.
