### ISSUE TITLE
Draft Candidate V3.2 (Conformance Claim)

### ISSUE THREAD

**Issue by The-Fiona** [commoncriteria/mobile-device#3]
Draft Candidate V3.2 https://commoncriteria.github.io/pp/mobile-device/mobile-device-release.pdf
States in Section 2. 
"This PP is conformant to Parts 2 (extended) and 3 (conformant) of Common Criteria Version 3.1, Revision 5."

Since ALC_TSU_EXT is included, then the claim should be 
"This PP is conformant to Parts 2 (extended) and 3 (**extended**) of Common Criteria Version 3.1, Revision 5."

**Comment by jeffblank** [comment]
Regarding ALC_TSU_EXT, the authors may want to consider using ALC_FLR instead: there were updates to its text, particularly in ALC_FLR.3.6C in CC Part 3 3.1R5.

**Comment by woodbe** [comment]
It has been nearly a year and I don't see this as having been updated. I get not making the ALC_FLR change at this point given the hope to publish 3.2 soon, but this should be extended, especially after the same thing was pointed out in an App eval as needing to be extended there for what I can only imagine has to be the same reason (only one that makes sense).

**Comment by lewyble** [comment]
@dmhale1 - Can you please let me know if any additional changes to the PP are needed or if this issue has been addressed please close out the comment. Thanks!

**Comment by dmhale1** [comment]
For this version we are leaving ALC_TSU_EXT so ""This PP is conformant to Parts 2 (extended) and 3 (extended) of Common Criteria Version 3.1, Revision 5." is correct.

**Comment by dmhale1** [comment]
Sorry, I closed it by mistake. Need to update to: This PP is conformant to Parts 2 (extended) and 3 (**extended**) of Common Criteria Version 3.1, Revision 5.

**Comment by lewyble** [comment]
Updated to: This PP is conformant to Parts 2 (extended) and 3 (extended) of Common Criteria Version 3.1, Revision 5.
