### ISSUE TITLE
Hotspot test typo

### ISSUE THREAD

**Issue by woodbe** [commoncriteria/mobile-device#33]
https://github.com/commoncriteria/mobile-device/blob/954ded4330200e30c1e4b35b7b7398b6d6a3598c/input/mobile-device.xml#L6699-L6700

On the beginning of 6700, there is a "0" based on the selections. I'm not exactly sure what should go here (and GitHub seems to bomb out at 6626 lines in the online editor).

**Comment by lewyble** [comment]
Fixed.
