### ISSUE TITLE
FPT_TUD_EXT.2.3 test 4

### ISSUE THREAD

**Issue by woodbe** [commoncriteria/mobile-device#37]
https://github.com/commoncriteria/mobile-device/blob/954ded4330200e30c1e4b35b7b7398b6d6a3598c/input/mobile-device.xml#L7652-L7656

What exactly is the point of this test? The SFRs 2.1-2.3 are about system software, not applications, so it isn't clear what the application here is supposed to be. It looks like this is a variation of the test activity for 2.4 which I think is better written.

It looks like this specific test should be removed.

**Comment by lewyble** [comment]
test 4 was removed
