### ISSUE TITLE
FAU_SAR.1 to mandatory

### ISSUE THREAD

**Issue by woodbe** [commoncriteria/mobile-device#41]
This has been objective for some time, but it seems like it should be made mandatory. Requiring audit records to be generated but then not having any way to actually review them seems to make the point of having FAU_GEN.1 required to be a waste of time.

Since this doesn't mean that there has to be a UI, but that they must be available to an MDM Agent, this shouldn't be too much of a problem as long as there is a way to retrieve the information.

I would think that this also has to be something that is collectible under normal usage scenarios for the administrator (i.e. must be able to be collected remotely).

**Comment by lewyble** [comment]
This will be moved to mandatory before the next update, so that the TC has an opportunity to comment on it.
