### ISSUE TITLE
FPT_TUD_EXT.4.2 moved to FPT_TUD_EXT.5.1

### ISSUE THREAD

**Issue by woodbe** [commoncriteria/mobile-device#5]
https://github.com/commoncriteria/mobile-device/blob/9aa95cab5852a69bddd18540e53096e4f54f542c/input/mobile-device.xml#L5289

This requirement is specifically about the TSF software, while FPT_TUD_EXT.4.1 is specifically about the mobile apps on the device. But because 4.2 is hierarchical to 4.1, it is not possible to claim 4.2 without also claiming 4.1. Given that these are two completely independent update systems (OS updates are generally not going to use the same process as app updates on mobile devices), there is no reason for these to be bound together. Android does not support 4.1, and so is precluded (at this time) from being able to claim 4.2 (which can be supported).

In v3.0 of the PP, this was requirement FPT_TUD_EXT.2.7, and since 2.1-4 were claimed, the hierarchical argument was not a problem, but now the current interpretations are not allowing this claim.

To that end, FPT_TUD_EXT.4.2 should become FPT_TUD_EXT.5.1 which would remove the dependency and make it possible to claim this option.

**Comment by lewyble** [comment]
Change made in version 3.2.
