### ISSUE TITLE
Use Case 1 edit

### ISSUE THREAD

**Issue by woodbe** [commoncriteria/mobile-device#6]
Table 9 in USE CASE 1 has an option for FMT_MOF_EXT.1.2 Function 4/FMT_SMF_EXT.1.1 Function 4 to "Assign GPS". This seems redundant since the management table line #21 already covers location services and would cover both GPS and additional methods (such as Wi-Fi or Bluetooth positioning).

Should this be removed?

**Comment by lewyble** [comment]
GPS removed as a mandatory assignment for Function 4 and is covered by Function 21. For use case 1 - function 21 (location services) is now mandatory to be configured by the admin, if the device is enrolled in management.
