### ISSUE TITLE
Remove or update message digest size in FCS_COP.1(2) and FCS_COP.1(4)

### ISSUE THREAD

**Issue by QuentinGouchet** [commoncriteria/mobile-device#7]
In FCS_COP.1(2) and (4), a selection has to be made by the ST author regarding the message digest size of the message-digest (SHA) and keyed-message digest (HMAC) operations.

Regarding the message digest (SHA), it is redundant to specify the size of the output, since the specification of the hash function already specifies the output, i.e. SHA-256 will have a 256-bit message digest output. It is implicit to the selection of the hash function.

Regarding keyed-message digests (HMAC), it is somehow implicit. Currently, the CAVP allows labs to test HMAC-SHA will the full/default length message digest, and some truncation.

I would suggest to either remove the message digest size part of both SFRs, or align with the tag lengths per HMAC-SHA that CAVP allows to be tested (see section 6.1, bullet 7 of https://csrc.nist.gov/csrc/media/projects/cryptographic-algorithm-validation-program/documents/mac/hmacvs.pdf).

**Comment by lewyble** [comment]
@dmhale1 - thoughts?

**Comment by dmhale1** [comment]
I will check on this one and get back to you.

**Comment by dmhale1** [comment]
The issue was truncation and we wanted to be clear that the full digest was needed (and in the cert). Understand the redundancy claim but  don’t see this hurting anything so we want to  leave it as is. Plus, it matches how we do all these requirements.
