### ISSUE TITLE
FCS_STG_EXT.1 key secret consistency?

### ISSUE THREAD

**Issue by woodbe** [commoncriteria/mobile-device#71]
FCS_STG_EXT.1.2 & FCS_STG_EXT.1.3 both use "keys or secrets"

FCS_STG_EXT.1.4 & FCS_STG_EXT.1.5 still use "key/secret"

The MDF v3.2 used "key/secret" in all the requirements. It seems like the remaining ones should be changed just to be consistent in how it reads (it reads fine either way, it is just switching, even if you are talking singular, seems odd in the middle of the same SFR).

**Comment by crpezol** [comment]
fixed
