### ISSUE TITLE
FIA_X509_EXT.1.1 edits

### ISSUE THREAD

**Issue by woodbe** [commoncriteria/mobile-device#72]
Trivial change, but the 4th bullet is missing a period (.) at the end of the line.

    The  TSF shall validate that any CA certificate includes caSigning purpose in the key usage field

The last three subbullets have EKU instead of extendedKeyUsage. This seems to have been introduced in v3.2 (v3.1 has it written out fully). Either one is fine, but it should be consistently used (probably the full write-out unless there is a definition for it somewhere else).

**Comment by crpezol** [comment]
fixed
