### ISSUE TITLE
FMT_SMF Table 7, item 35

### ISSUE THREAD

**Issue by woodbe** [commoncriteria/mobile-device#73]
the sentence ends with "key/secret" while earlier in the sentence it states "keys or secrets". For consistency is should be "key or secret".

**Comment by crpezol** [comment]
just to be clear are you suggesting it should be "approve exceptions for destruction of keys or secrets by applications that did not import the key or secret" or more like "approve exceptions for destruction of a key or secret by an application that did not import the key or secret"?

**Comment by lewyble** [comment]
commit: 1da4984
