### ISSUE TITLE
FPT_TUD_EXT.1.1 missing period at the end

### ISSUE THREAD

**Issue by woodbe** [commoncriteria/mobile-device#74]
The FPT_TUD_EXT.1.1 requirement is missing a period at the end of the sentence.

**Comment by crpezol** [comment]
I'm seeing the period in the HTML and XML, was it a different SFR?

**Comment by woodbe** [comment]
FPT_TUD_EXT.2.1. 

Sorry

**Comment by crpezol** [comment]
got it
