### ISSUE TITLE
FTP_ITC_EXT.1.1 versions?

### ISSUE THREAD

**Issue by woodbe** [commoncriteria/mobile-device#75]
Should the 4th bullet listing in the first block and the second bullet in the second block listing "the Package for Transport Layer Security" have the version number?

The same goes for the PP-Module for VPN Client.

All the listings for the WLAN PPM have the full name and version, but the VPN Client and TLS Package are missing this information.

**Comment by crpezol** [comment]
references to modules and packages have been updated
