### ISSUE TITLE
FCS_COP.1.1/HASH "bits"

### ISSUE THREAD

**Issue by woodbe** [commoncriteria/mobile-device#77]
The bit size selection:

>  [160 and [selection: 256 bits, 384 bits, 512 bits, no other message digest sizes ]]

should have "bits" at the 160 as well since it doesn't make sense to have it only defined on the selections and not the mandatory length, or move "bits" to outside the selection completely.

>  [160 **bits** and [selection: 256 bits, 384 bits, 512 bits, no other message digest sizes ]]

or

>  [160 and [selection: 256, 384, 512, no other message digest sizes ]] **bits**

There is also an extra space after "no other message digest sizes"

**Comment by lewyble** [comment]
commit: 7a634da
