### ISSUE TITLE
FCS_COP.1(5) EA

### ISSUE THREAD

**Issue by lewyble** [commoncriteria/mobile-device#8]
Updated fcs_cop.1(5) per TD 366, but for the EA there were lines/paragraphs that were not "included" in the TD, meaning not strike-outed. Should I assume that if not in the TD means to delete from EA (these parts are currently commented out)?

https://github.com/commoncriteria/mobile-device/blob/d03ee2ff59d588c8168a3ed2b5c70ad8db68f82b/input/mobile-device.xml#L2140

**Comment by jmcdaniels** [comment]
I reviewed the TD, yes that assumption is correct.
