### ISSUE TITLE
Odd ordering in Technical Terms

### ISSUE THREAD

**Issue by woodbe** [commoncriteria/mobile-device#9]
Several biometric terms end up at the top of the list due to beginning with "(". It would seem these parenthesis should be removed from the "(Biometric)" so they are properly ordered.

https://github.com/commoncriteria/mobile-device/blob/4de420d946cd352646d3a73ed2a9f296db02ffeb/input/mobile-device.xml#L295

https://github.com/commoncriteria/mobile-device/blob/4de420d946cd352646d3a73ed2a9f296db02ffeb/input/mobile-device.xml#L348

https://github.com/commoncriteria/mobile-device/blob/4de420d946cd352646d3a73ed2a9f296db02ffeb/input/mobile-device.xml#L416

If it is felt that it is necessary to have "Modality" instead of "Biometric Modality" for clarity later, just add "(Modality)" to the end of the line, similar to how (ASLR) is added to Address Space Layout Randomization.

Another option would be to add the (Biometrics) at the end as is done with "Enrollment (Biometrics)".
https://github.com/commoncriteria/mobile-device/blob/4de420d946cd352646d3a73ed2a9f296db02ffeb/input/mobile-device.xml#L258

**Comment by lewyble** [comment]
Fixed.

Modified to put "(Biometrics)" at the end, since the alphabetizing is done by the transforms.
